# Generated by Django 5.0 on 2025-12-19 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.departamento'),
            preserve_default=False,
        ),
    ]
