# Generated by Django 5.0 on 2026-01-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='descripcion',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='departamentos/'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='fecha_de_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nro_empleados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
