# Generated by Django 6.0.1 on 2026-01-11 21:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Contenido')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Mostrar en menú')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta título')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta descripción')),
                ('is_home', models.BooleanField(default=False, verbose_name='Es página principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['order', 'title'],
            },
        ),
    ]
